[project]
name = "portfolio-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiogram>=3.30.0",
    "alembic>=1.18,<2",
    "asyncpg>=0.31.0",
    "pydantic-settings>=2.14.2",
    "sqlalchemy[asyncio]>=2.0,<2.2",
]
