"""create initial database schema

Revision ID: a42b10a559e6
Revises: 
Create Date: 2026-07-20 22:14:23.955370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'a42b10a559e6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

lead_status_enum = postgresql.ENUM(
    "new",
    "in_progress",
    "waiting_for_client",
    "closed",
    name="lead_status",
    create_type=False,
)

notification_type_enum = postgresql.ENUM(
    "new_lead",
    "lead_status_changed",
    "lead_closed",
    name="notification_type",
    create_type=False,
)

delivery_status_enum = postgresql.ENUM(
    "pending",
    "delivered",
    "failed",
    name="delivery_status",
    create_type=False,
)


def upgrade() -> None:
    """Upgrade schema."""

    bind = op.get_bind()

    lead_status_enum.create(bind, checkfirst=True)
    notification_type_enum.create(bind, checkfirst=True)
    delivery_status_enum.create(bind, checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_settings',
    sa.Column(
        "admin_telegram_id",
        sa.BigInteger(),
        autoincrement=False,
        nullable=False,
    ),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('notifications_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('admin_telegram_id', name=op.f('pk_admin_settings'))
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_telegram_user_id'), 'users', ['telegram_user_id'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('contact_name', sa.String(length=255), nullable=False),
    sa.Column('project_description', sa.Text(), nullable=False),
    sa.Column('required_features', sa.Text(), nullable=False),
    sa.Column('deadline', sa.String(length=255), nullable=False),
    sa.Column('budget', sa.String(length=255), nullable=False),
    sa.Column('client_comment', sa.Text(), nullable=True),
    sa.Column(
    "status",
    lead_status_enum,
    server_default="new",
    nullable=False,
    ),
    sa.Column('close_comment', sa.Text(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_leads_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leads'))
    )
    op.create_index(op.f('ix_leads_status'), 'leads', ['status'], unique=False)
    op.create_index('ix_leads_status_created_at', 'leads', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_leads_user_id'), 'leads', ['user_id'], unique=False)
    op.create_table('lead_admin_comments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('lead_id', sa.BigInteger(), nullable=False),
    sa.Column('admin_telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('is_sent_to_client', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('delivery_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_lead_admin_comments_lead_id_leads'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lead_admin_comments'))
    )
    op.create_index('ix_lead_admin_comments_lead_created_at', 'lead_admin_comments', ['lead_id', 'created_at'], unique=False)
    op.create_table('lead_status_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('lead_id', sa.BigInteger(), nullable=False),
    sa.Column(
    "old_status",
    lead_status_enum,
    nullable=True,
    ),
    sa.Column(
    "new_status",
    lead_status_enum,
    nullable=False,
    ),
    sa.Column('admin_telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_lead_status_history_lead_id_leads'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lead_status_history'))
    )
    op.create_index('ix_lead_status_history_lead_created_at', 'lead_status_history', ['lead_id', 'created_at'], unique=False)
    op.create_table('notification_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('lead_id', sa.BigInteger(), nullable=False),
    sa.Column('recipient_telegram_id', sa.BigInteger(), nullable=False),
    sa.Column(
    "notification_type",
    notification_type_enum,
    nullable=False,
    ),
    sa.Column(
    "delivery_status",
    delivery_status_enum,
    server_default="pending",
    nullable=False,
    ),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_notification_log_lead_id_leads'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_log'))
    )
    op.create_index('ix_notification_log_lead_created_at', 'notification_log', ['lead_id', 'created_at'], unique=False)
    op.create_index('ix_notification_log_recipient_created_at', 'notification_log', ['recipient_telegram_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notification_log_recipient_created_at', table_name='notification_log')
    op.drop_index('ix_notification_log_lead_created_at', table_name='notification_log')
    op.drop_table('notification_log')
    op.drop_index('ix_lead_status_history_lead_created_at', table_name='lead_status_history')
    op.drop_table('lead_status_history')
    op.drop_index('ix_lead_admin_comments_lead_created_at', table_name='lead_admin_comments')
    op.drop_table('lead_admin_comments')
    op.drop_index(op.f('ix_leads_user_id'), table_name='leads')
    op.drop_index('ix_leads_status_created_at', table_name='leads')
    op.drop_index(op.f('ix_leads_status'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_telegram_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('admin_settings')

    bind = op.get_bind()

    delivery_status_enum.drop(bind, checkfirst=True)
    notification_type_enum.drop(bind, checkfirst=True)
    lead_status_enum.drop(bind, checkfirst=True)
    # ### end Alembic commands ###
